// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpB-XNsySjr4g3uQgVH1zMQ2RTQHRLCY',
    appId: '1:642854992033:web:e2813d4e617791ffcfd8e0',
    messagingSenderId: '642854992033',
    projectId: 'chess-app-9b415',
    authDomain: 'chess-app-9b415.firebaseapp.com',
    storageBucket: 'chess-app-9b415.firebasestorage.app',
    measurementId: 'G-KMSQTJWF8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuAOQRrIik_lic8RmdUcfEwnkD1SQ929w',
    appId: '1:642854992033:android:4256bbc27d095314cfd8e0',
    messagingSenderId: '642854992033',
    projectId: 'chess-app-9b415',
    storageBucket: 'chess-app-9b415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9DSkgtiIlAFyi26OIX6WD_7Ht4ziGw3U',
    appId: '1:642854992033:ios:1c8c6bcbff76a72bcfd8e0',
    messagingSenderId: '642854992033',
    projectId: 'chess-app-9b415',
    storageBucket: 'chess-app-9b415.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9DSkgtiIlAFyi26OIX6WD_7Ht4ziGw3U',
    appId: '1:642854992033:ios:1c8c6bcbff76a72bcfd8e0',
    messagingSenderId: '642854992033',
    projectId: 'chess-app-9b415',
    storageBucket: 'chess-app-9b415.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtpB-XNsySjr4g3uQgVH1zMQ2RTQHRLCY',
    appId: '1:642854992033:web:8759cb34d53be784cfd8e0',
    messagingSenderId: '642854992033',
    projectId: 'chess-app-9b415',
    authDomain: 'chess-app-9b415.firebaseapp.com',
    storageBucket: 'chess-app-9b415.firebasestorage.app',
    measurementId: 'G-C75WFPLQX0',
  );
}
